# Generated by Django 5.2.4 on 2025-07-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_email', models.EmailField(max_length=254, unique=True)),
                ('school_name', models.TextField(max_length=200)),
                ('school_description', models.TextField(max_length=6000)),
                ('facilities_and_clubs', models.TextField(max_length=4000)),
                ('school_admin_name', models.TextField(max_length=200)),
                ('school_admin_email', models.EmailField(max_length=254, unique=True)),
                ('school_address', models.TextField(max_length=600)),
                ('curriculum_type', models.TextField(max_length=60)),
                ('website_link', models.TextField(max_length=100)),
                ('date_est', models.DateField(blank=True)),
            ],
        ),
    ]
